#!/bin/bash
# Adding php wrapper
user="$1"
domain="$2"
wp_database="$3"
wp_database_user="$4"
wp_password="$5"
home_dir="$6"
wp_link="https://wordpress.org/latest.zip"
wp_path="/home/$user/web/$domain/public_html"
wp_file="$wp_path/wordpress.zip"
cd $home_dir
wget $wp_link -O $wp_file
unzip $wp_file -d $wp_path
mv $wp_path/wordpress/* $wp_path
rm $wp_file
rm -rf $wp_path/wordpress/ $wp_path/index.html
#chmod -R 777 $wp_path
chown -R $user:$user /home/$user/web
cp $wp_path/wp-config-sample.php $wp_path/wp-config.php
perl -pi -e "s/database_name_here/$wp_database/g" $wp_path/wp-config.php
perl -pi -e "s/username_here/$wp_database_user/g" $wp_path/wp-config.php
perl -pi -e "s/password_here/$wp_password/g" $wp_path/wp-config.php
